Ashish = input("When is your birthday Ashish?")
shingini = input("When is your birthday Shingini?")
usha = input("When is your birthday Usha?")
Siddhartha = input("When is your birthday Siddhartha?")
Sachin = input("When is your birthday Sachin?")
print("so, ashish's birthday is on " + Ashish)
print(" shingini's birthday is on " + shingini)
print(" usha's birthday is on " + usha)
print("23 nov siddhartha's birthday is on " + Siddhartha)
print(" sachin's birthday is on " + Sachin)